version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: clozyt-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
